schema = 3

[mod]
  [mod."github.com/fatih/color"]
    version = "v1.18.0"
    hash = "sha256-pP5y72FSbi4j/BjyVq/XbAOFjzNjMxZt2R/lFFxGWvY="
  [mod."github.com/google/go-github/v57"]
    version = "v57.0.0"
    hash = "sha256-ak3QrhL4a763Omr5Hj/MewYNIbiJ8ooRXdOOInFRVUM="
  [mod."github.com/google/go-querystring"]
    version = "v1.2.0"
    hash = "sha256-F/Ve4oDaEqho8RryvdGSRR22/DbYHWZQa6M60n6oSYM="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.14"
    hash = "sha256-JC60PjKj7MvhZmUHTZ9p372FV72I9Mxvli3fivTbxuA="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.14.1"
    hash = "sha256-6NzhXCCD1Qhj05WHbCDxH5hwfNM6psoAk7uIxm7N55E="
  [mod."github.com/urfave/cli/v3"]
    version = "v3.6.2"
    hash = "sha256-GeTwfmXv2okvX2kmMREozvH4PH6ihPNVFSNSWrW+gyQ="
  [mod."golang.org/x/oauth2"]
    version = "v0.34.0"
    hash = "sha256-5eqpGGxJ7FJsPmfRek6roeGmkWHBMJaWYXyz8gXJsS4="
  [mod."golang.org/x/sys"]
    version = "v0.40.0"
    hash = "sha256-KDe+wMr7dfMFwKMJEljzk+f82pQWFFPoFHivjD7qJGg="
  [mod."golang.org/x/tools"]
    version = "v0.26.0"
    hash = "sha256-drBvWfz/yBxABO9LUiLLV2ra5rw5VL2FrEjprdOtJhg="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
